### ISSUE TITLE
OpenApi support for Arrays of Objects

### ISSUE THREAD

**Issue by jearles** [djfdyuruiry/ts-lambda-api#17]
Thank you for your fabulous extension of lambda-api. We are using it inside a Typescript-build lambda application and it's working great.

I was very excited when I saw your initial commits using OpenApi, and I am working through documenting our APIs.

I hit a small snag when I was looking to document a GET API that returns a collection of DTO objects. I was hoping to be able to use class, with its example concept, and indicate that we were returning an array type. But that did not appear to be an option.

I ended up with a work around:

`@apiResponse(200, { type: 'object-array', example: JSON.stringify(OFFERS_ARRAY, undefined, 2), description: "Details of the offers" })
`

This seems to render fine in Swagger UI, but when I use Swagger Edit I see three errors being reported on my object-array APIs:

> Schemas with 'type: array', require a sibling 'items: ' field

Do you have plans to add support for this field? If not, what is your recommended approach to documenting a "list" API?

Thanks again... I can't wait to see where ts-lambda-api goes next.

**Comment by djfdyuruiry** [comment]
Hi @jearles 

I am delighted to hear that you are using my framework, and it is working well for you.

Yes, I have replicated the issues you are seeing. The OpenAPI spec generator isn't adding an `items` field to the schema for array types, and the issue with the `example` static method not accepting arrays is that it is expecting the return value to be an object.

I have patched both these issues in a new PR, it will allow any type to be returned from an `example` method and add an items field to array schemas.

 I will hopefully have it merged and published to NPM within the next few days. Hopefully this will help you out.  :)

**Comment by jearles** [comment]
Thank you, very much! Our project is still targeting Node 8, but with the recent announcement we should be upgrading to 10 soon. I'm sure your fix did the trick though, so you may close the ticket. I appreciate the prompt response.

**Comment by jearles** [comment]
Just finished our upgrade to Node 10.x runtime, and ts-lambda-api 6.1

Verified!

**Comment by djfdyuruiry** [comment]
Fantastic, thanks for letting me know.
