### ISSUE TITLE
Feature request: pathParam and queryParam additional property support

### ISSUE THREAD

**Issue by jearles** [djfdyuruiry/ts-lambda-api#19]
As I continue to document my APIs I am hitting areas that use path and query params. The current decorators work great to identify the name of the parameters, but it would help flesh out the documentation if we could add the 'description' for both and 'required' for queryParam.

Description is (in my opinion) of higher priority and required could come later if you start to look at things like examples for query parameters.

Not trying to add more work to your plate... just providing feedback for your roadmap. If desired I might be able to make time to submit a PR, but I also can appreciate you wanting to retain full control over your project and feature roadmap.

Thanks again.

**Comment by djfdyuruiry** [comment]
This sounds like a very sensible suggestion to me. I am happy if you want to submit a PR, all contributions are welcome. :) I will probably have some time soon anyway to look at this, so watch this space if you don't have time.

**Comment by djfdyuruiry** [comment]
@jearles I have added OpenAPI parameter metadata functionality to the latest release: https://github.com/djfdyuruiry/ts-lambda-api/releases/tag/v0.6.2

Read the docs and let me know how this works out for you

**Comment by jearles** [comment]
I upgraded to 0.6.2 today and checked in a couple of parameter descriptions. Everything looks great so far, and your attention to detail is spot on as usual.

I'll try out a few more of the options tomorrow but I am quite happy with what I see documented. Excellent work. Thank you; you may close the ticket.

**Comment by djfdyuruiry** [comment]
Good to hear, glad you things working :+1:
