### ISSUE TITLE
Question: is this necessary to inject all controllers outside of handlers via DI?

### ISSUE THREAD

**Issue by alexsun8899** [djfdyuruiry/ts-lambda-api#41]
Thanks for your efforts and time to build such a good library. I come from express API and lambda API, well done on swagger integration and decorator based design:)

Each lambda function serves one job only, we say there is an API project consisted of 50 endpoints and each endpoint connected to a lambda handler. DI container lives outside of handlers, only one endpoint will be used by each lambda invocation, so seems injecting of all controllers creates sth that won't be fully used by lambda request, which consumes more memory and takes longer to initialise stateful objects at startup. 

- Can you please share a best practice for using DI in a serverless environment?

- In above example, instead of registering all controllers, is this better to register a single endpoint per lambda handler? Can you please confirm it? 

Thank you.

**Comment by djfdyuruiry** [comment]
Hi @alexsun8899 👋 

If the architecture you have designed uses a single Lambda per endpoint you can indeed improve performance by manually loading controllers, see: https://github.com/djfdyuruiry/ts-lambda-api#loading-controllers

This framework supports both multi-controller Lambdas and simple single-endpoint/controller scenarios.

A suggestion here would be to use something in each lambda handler that tells the main entry-point to load different controllers based on the function of the lambda. You could use environment variables to do this:

```ts
import { Container } from 'inversify';
import { ApiLambdaApp, ApiRequest, AppConfig } from 'ts-lambda-api';
import { AppController } from './controllers/AppController';

// setup
const appConfig = new AppConfig();
appConfig.base = '/api/v1';
appConfig.version = 'v1';

const appContainer = new Container({ autoBindInjectable: false });

// configure controller
const lambdaFunction = process.env.LAMBDA_FUNCTION

if (lambdaFunction  === "people") {
  const peopleController = new PeopleController();

  appContainer.bind(PeopleController)
    .toConstantValue(peopleController );
} else if (lambdaFunction == "cars") {
  const carsController = new CarsController();

  appContainer.bind(CarsController)
    .toConstantValue(carsController);
}

// handle request
const app = new ApiLambdaApp(undefined, appConfig, appContainer);

export const lambdaHandler = async (event: ApiRequest, context: any) => {
	return await app.run(event, context);
};
```

You could then define different env vars for each lambda in your terraform or in AWS console (whatever tool you are using to deploy your Lambdas will support this)

**Comment by djfdyuruiry** [comment]
Going to close this now - let me know if you need any other guidance
