### ISSUE TITLE
Question: can i use this framework together with serverless framework?

### ISSUE THREAD

**Issue by fernando1989mg** [djfdyuruiry/ts-lambda-api#51]
I don't see in the readme instructions to use it together with the serverless framework, is it possible?

**Comment by revbingo** [comment]
@fernando1989mg not the maintainer, but yes, serverless is perfect for this.  You just need a handler function that creates the `ApiLambdaApp` and calls `.run(event,context)` (as documented in the README), and then reference that handler function from your `serverless.yml`
