### ISSUE TITLE
How to embed swagger ui ?

### ISSUE THREAD

**Issue by gartcimore** [djfdyuruiry/ts-lambda-api#54]
Is there a way to use the generated open-api specification and display it using swagger-ui-express maybe ?

**Comment by gartcimore** [comment]
So I found that I should use https://www.npmjs.com/package/ts-lambda-api-local but the swagger ui displayed is empty, no methods seems to be found

**Comment by djfdyuruiry** [comment]
If you have an example of swagger ui not loading that you can share please reopen
