### ISSUE TITLE
Question: Local storage (cls-hooked) setup to log request/response data

### ISSUE THREAD

**Issue by hemanth1226** [djfdyuruiry/ts-lambda-api#56]
I am trying to use "https://www.npmjs.com/package/cls-hooked" in my project to store request and response data and log them. But i am facing issues integrating it. Do you have any option to store the data and retrieve them in controllers or services and log the data?

This is what i am doing:

```javascript
import * as cls from "cls-hooked";
const clsNamespace = cls.createNamespace("app");
app.configureApi((api) => {
  api.use((req: Request, res: Response, next: () => void) => {
    clsNamespace.bind(req as any);
    clsNamespace.run(() => {
      clsNamespace.set("url", url);
      next();
    });
});
```

When i am trying to access the stored data in a component, i am getting the value as undefined.
```javascript
import * as cls from "cls-hooked";
private clsNamespace = cls.getNamespace("app");
console.log(clsNamespace.get('url')) // prints undefined
```

**Comment by djfdyuruiry** [comment]
Hello

I am not familiar with this framework - but where/when is the second block of code being executed. Is it in an endpoint?

**Comment by hemanth1226** [comment]
Hi, thank you for your time. Yes it is inside an endpoint. 

I am using this framework for Continuation Local Storage. I have tried using [async-hooks](https://github.com/nodejs/node/blob/master/doc/api/async_hooks.md) as well but that didn't work either.  

I have attached a sample zip file where i added console logs. I hope this helps understanding the issue. Please let me know if this doesn't help.  

[test-lambda-api.zip](https://github.com/djfdyuruiry/ts-lambda-api/files/6402735/test-lambda-api.zip)

Thanks!

**Comment by Muthuveerappanv** [comment]
@hemanth1226 @djfdyuruiry was able to resolve this using a `runPromise` option within the `cls-hooked` library 
```
app.configureApi((api) => {
  api.use((req: Request, res: Response, next: () => void) => {
    clsNamespace.bind(req as any);
    clsNamespace.bind(res as any);
    
    clsNamespace.runPromise(() => {
      clsNamespace.set("x-amzn-trace-id", "test id");
      // console.log(clsNamespace, "inside run");
      return Promise.resolve(next());
    });
  });
});
```
